version: '3.8'

services:
  mongodb_server_erp: 
    image: wonbot/shinheeagv:mongodb
    container_name: mongodb_server_erp
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27014:27017
    volumes:
      - /shinhee_erp:/data/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

  overtime-tracking:
    image: wonbot/shinheeagv:overtime-tracking
    container_name: overtime-tracking
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - TZ=Asia/Seoul
    ports:
      - 4000:3000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mongodb_server_erp
    restart: always