version: '3.8'

services:
  mongodb_server_erp: 
    image: wonbot/shinheeagv:mongodb
    container_name: mongodb_server_erp
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27014:27017
    volumes:
      - /shinhee_erp:/data/db
    restart: always

  overtime-tracking:
    image: wonbot/shinheeagv:overtime-tracking
    container_name: overtime-tracking
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
    ports:
      - 3000:3000
    depends_on:
      - mongodb_server_erp
    restart: always